module.exports = {
  content: ["_site/**/*.html", "_site/**/*.js"],
  css: ["_site/assets/css/*.css"],
  output: "_site/assets/css/",
  skippedContentGlobs: ["_site/assets/**/*.html"],
  safelist: [
    // Bootstrap image & layout utilities used dynamically via Liquid includes
    "img-fluid",
    "img-thumbnail",
    "rounded",
    "rounded-circle",
    "z-depth-1",
    "z-depth-2",
    "float-left",
    "float-right",
    "float-none",
    // Bootstrap responsive utilities that may be dynamically applied
    /^float-/,
    /^rounded/,
    /^z-depth-/,
    // Cybersecurity Explained directory — classes applied via Liquid/JS at runtime
    /^explained-/,
    // Cybersecurity Calendar — grid, cells, chips, modal, agenda all generated by JS at runtime
    /^cal-/,
  ],
};
