#!/usr/bin/env python3
"""
fetch_cyber_conferences.py
Source-of-truth registry of US cybersecurity conferences.
Writes: scripts/output/conferences_raw.json
"""

import json
import os

# ---------------------------------------------------------------------------
# CONFERENCES — edit this list to add / remove / update entries
# ---------------------------------------------------------------------------
CONFERENCES = [
    {
        "id": "cactuscon-14",
        "name": "CactusCon 14",
        "slug": "cactuscon-14",
        "short_description": "Community-focused security conference in the Phoenix metro area.",
        "start_date": "2026-03-13",
        "end_date": "2026-03-14",
        "city": "Mesa",
        "state": "AZ",
        "venue": "Mesa Convention Center",
        "website_url": "https://www.cactuscon.com/",
        "cfp_url": "",
        "registration_cost_min": 0,
        "registration_cost_max": 0,
        "registration_cost_notes": "Free community event",
        "is_estimated_pricing": False,
        "category_tags": ["community", "hacking"],
        "data_confidence": "medium",
        "last_verified": "2026-03-14",
    },
    {
        "id": "shmoocon-2026",
        "name": "ShmooCon 2026",
        "slug": "shmoocon-2026",
        "short_description": "East Coast hacker convention focused on offensive/defensive topics.",
        "start_date": "2026-03-13",
        "end_date": "2026-03-15",
        "city": "Washington",
        "state": "DC",
        "venue": "Marriott Wardman Park",
        "website_url": "https://www.shmoocon.org/",
        "cfp_url": "",
        "registration_cost_min": 150,
        "registration_cost_max": 200,
        "registration_cost_notes": "Estimated — lottery ticket system",
        "is_estimated_pricing": True,
        "category_tags": ["hacking", "community"],
        "data_confidence": "medium",
        "last_verified": "2026-03-14",
    },
    {
        "id": "secureworld-dallas-2026",
        "name": "SecureWorld Dallas 2026",
        "slug": "secureworld-dallas-2026",
        "short_description": "Regional enterprise security conference with CPE-eligible sessions.",
        "start_date": "2026-03-25",
        "end_date": "2026-03-26",
        "city": "Dallas",
        "state": "TX",
        "venue": "Irving Convention Center",
        "website_url": "https://www.secureworldexpo.com/events/dallas",
        "cfp_url": "",
        "registration_cost_min": 195,
        "registration_cost_max": 395,
        "registration_cost_notes": "Estimated — full conference pass",
        "is_estimated_pricing": True,
        "category_tags": ["enterprise", "training"],
        "data_confidence": "medium",
        "last_verified": "2026-03-14",
    },
    {
        "id": "ics-security-summit-2026",
        "name": "ICS Security Summit (SANS)",
        "slug": "ics-security-summit-2026",
        "short_description": "SANS summit focused on industrial control systems and OT/ICS security.",
        "start_date": "2026-03-23",
        "end_date": "2026-03-24",
        "city": "Orlando",
        "state": "FL",
        "venue": "TBD",
        "website_url": "https://www.sans.org/cyber-security-summit/ics/",
        "cfp_url": "",
        "registration_cost_min": 595,
        "registration_cost_max": 995,
        "registration_cost_notes": "Estimated — SANS summit pricing",
        "is_estimated_pricing": True,
        "category_tags": ["enterprise", "training"],
        "data_confidence": "low",
        "last_verified": "2026-03-14",
    },
    {
        "id": "bsides-sf-2026",
        "name": "BSides San Francisco 2026",
        "slug": "bsides-sf-2026",
        "short_description": "Community-organized security conference held alongside RSA.",
        "start_date": "2026-04-26",
        "end_date": "2026-04-27",
        "city": "San Francisco",
        "state": "CA",
        "venue": "City View at Metreon",
        "website_url": "https://bsidessf.org/",
        "cfp_url": "",
        "registration_cost_min": 25,
        "registration_cost_max": 75,
        "registration_cost_notes": "Estimated — low-cost community event",
        "is_estimated_pricing": True,
        "category_tags": ["community", "hacking"],
        "data_confidence": "medium",
        "last_verified": "2026-03-14",
    },
    {
        "id": "secureworld-atlanta-2026",
        "name": "SecureWorld Atlanta 2026",
        "slug": "secureworld-atlanta-2026",
        "short_description": "Regional enterprise security conference with CPE-eligible sessions.",
        "start_date": "2026-04-22",
        "end_date": "2026-04-23",
        "city": "Atlanta",
        "state": "GA",
        "venue": "Cobb Galleria Centre",
        "website_url": "https://www.secureworldexpo.com/events/atlanta",
        "cfp_url": "",
        "registration_cost_min": 195,
        "registration_cost_max": 395,
        "registration_cost_notes": "Estimated — full conference pass",
        "is_estimated_pricing": True,
        "category_tags": ["enterprise", "training"],
        "data_confidence": "medium",
        "last_verified": "2026-03-14",
    },
    {
        "id": "rsa-conference-2026",
        "name": "RSA Conference 2026",
        "slug": "rsa-conference-2026",
        "short_description": "The world's leading information security conference and expo.",
        "start_date": "2026-04-28",
        "end_date": "2026-05-01",
        "city": "San Francisco",
        "state": "CA",
        "venue": "Moscone Center",
        "website_url": "https://www.rsaconference.com/",
        "cfp_url": "https://www.rsaconference.com/call-for-submissions",
        "registration_cost_min": 895,
        "registration_cost_max": 2995,
        "registration_cost_notes": "Estimated — expo pass to full conference pass",
        "is_estimated_pricing": True,
        "category_tags": ["enterprise", "training"],
        "data_confidence": "medium",
        "last_verified": "2026-03-14",
    },
    {
        "id": "cybersecurity-summit-msp-2026",
        "name": "Cybersecurity Summit Minneapolis 2026",
        "slug": "cybersecurity-summit-msp-2026",
        "short_description": "Regional summit connecting cybersecurity leaders in the Twin Cities.",
        "start_date": "2026-04-01",
        "end_date": "2026-04-01",
        "city": "Minneapolis",
        "state": "MN",
        "venue": "TBD",
        "website_url": "https://cybersecuritysummit.com/summit/minneapolis/",
        "cfp_url": "",
        "registration_cost_min": 295,
        "registration_cost_max": 495,
        "registration_cost_notes": "Estimated",
        "is_estimated_pricing": True,
        "category_tags": ["enterprise"],
        "data_confidence": "low",
        "last_verified": "2026-03-14",
    },
    {
        "id": "hacknyc-2026",
        "name": "HACKNYC 2026",
        "slug": "hacknyc-2026",
        "short_description": "New York City security conference covering offensive and defensive topics.",
        "start_date": "2026-04-15",
        "end_date": "2026-04-16",
        "city": "New York",
        "state": "NY",
        "venue": "TBD",
        "website_url": "https://www.hacknyc.com/",
        "cfp_url": "",
        "registration_cost_min": 100,
        "registration_cost_max": 250,
        "registration_cost_notes": "Estimated",
        "is_estimated_pricing": True,
        "category_tags": ["hacking", "community"],
        "data_confidence": "low",
        "last_verified": "2026-03-14",
    },
    {
        "id": "layerone-2026",
        "name": "LayerOne 2026",
        "slug": "layerone-2026",
        "short_description": "Hacker-focused security conference in Los Angeles.",
        "start_date": "2026-05-22",
        "end_date": "2026-05-23",
        "city": "Los Angeles",
        "state": "CA",
        "venue": "TBD",
        "website_url": "https://www.layerone.org/",
        "cfp_url": "",
        "registration_cost_min": 75,
        "registration_cost_max": 150,
        "registration_cost_notes": "Estimated",
        "is_estimated_pricing": True,
        "category_tags": ["hacking", "community"],
        "data_confidence": "low",
        "last_verified": "2026-03-14",
    },
    {
        "id": "converge-detroit-2026",
        "name": "Converge Detroit 2026",
        "slug": "converge-detroit-2026",
        "short_description": "Midwest infosec conference focused on community and collaboration.",
        "start_date": "2026-05-14",
        "end_date": "2026-05-15",
        "city": "Detroit",
        "state": "MI",
        "venue": "TBD",
        "website_url": "https://www.convergeconference.org/",
        "cfp_url": "",
        "registration_cost_min": 50,
        "registration_cost_max": 150,
        "registration_cost_notes": "Estimated",
        "is_estimated_pricing": True,
        "category_tags": ["community", "hacking"],
        "data_confidence": "low",
        "last_verified": "2026-03-14",
    },
    {
        "id": "secureworld-chicago-2026",
        "name": "SecureWorld Chicago 2026",
        "slug": "secureworld-chicago-2026",
        "short_description": "Regional enterprise security conference with CPE-eligible sessions.",
        "start_date": "2026-05-20",
        "end_date": "2026-05-21",
        "city": "Chicago",
        "state": "IL",
        "venue": "Hyatt Regency O'Hare",
        "website_url": "https://www.secureworldexpo.com/events/chicago",
        "cfp_url": "",
        "registration_cost_min": 195,
        "registration_cost_max": 395,
        "registration_cost_notes": "Estimated — full conference pass",
        "is_estimated_pricing": True,
        "category_tags": ["enterprise", "training"],
        "data_confidence": "medium",
        "last_verified": "2026-03-14",
    },
    {
        "id": "infiltrate-2026",
        "name": "Infiltrate 2026",
        "slug": "infiltrate-2026",
        "short_description": "Deeply technical offensive security conference in Miami.",
        "start_date": "2026-05-07",
        "end_date": "2026-05-08",
        "city": "Miami",
        "state": "FL",
        "venue": "Loews Miami Beach Hotel",
        "website_url": "https://infiltratecon.com/",
        "cfp_url": "",
        "registration_cost_min": 1500,
        "registration_cost_max": 2500,
        "registration_cost_notes": "Estimated — premium offensive security conference",
        "is_estimated_pricing": True,
        "category_tags": ["hacking", "training"],
        "data_confidence": "low",
        "last_verified": "2026-03-14",
    },
    {
        "id": "sans-dfir-2026",
        "name": "SANS DFIR Summit 2026",
        "slug": "sans-dfir-2026",
        "short_description": "SANS summit focused on digital forensics and incident response.",
        "start_date": "2026-06-25",
        "end_date": "2026-06-26",
        "city": "Austin",
        "state": "TX",
        "venue": "TBD",
        "website_url": "https://www.sans.org/cyber-security-summit/dfir/",
        "cfp_url": "",
        "registration_cost_min": 595,
        "registration_cost_max": 995,
        "registration_cost_notes": "Estimated — SANS summit pricing",
        "is_estimated_pricing": True,
        "category_tags": ["enterprise", "training"],
        "data_confidence": "low",
        "last_verified": "2026-03-14",
    },
    {
        "id": "circlecitycon-2026",
        "name": "Circle City Con 2026",
        "slug": "circlecitycon-2026",
        "short_description": "Hacker and security community conference in Indianapolis.",
        "start_date": "2026-06-05",
        "end_date": "2026-06-07",
        "city": "Indianapolis",
        "state": "IN",
        "venue": "TBD",
        "website_url": "https://circlecitycon.org/",
        "cfp_url": "",
        "registration_cost_min": 75,
        "registration_cost_max": 175,
        "registration_cost_notes": "Estimated",
        "is_estimated_pricing": True,
        "category_tags": ["hacking", "community"],
        "data_confidence": "low",
        "last_verified": "2026-03-14",
    },
    {
        "id": "nolacon-2026",
        "name": "NOLACon 2026",
        "slug": "nolacon-2026",
        "short_description": "New Orleans hacker and security community conference.",
        "start_date": "2026-06-12",
        "end_date": "2026-06-14",
        "city": "New Orleans",
        "state": "LA",
        "venue": "TBD",
        "website_url": "https://nolacon.com/",
        "cfp_url": "",
        "registration_cost_min": 50,
        "registration_cost_max": 150,
        "registration_cost_notes": "Estimated",
        "is_estimated_pricing": True,
        "category_tags": ["hacking", "community"],
        "data_confidence": "low",
        "last_verified": "2026-03-14",
    },
    {
        "id": "central-ohio-infosec-2026",
        "name": "Central Ohio InfoSec Summit 2026",
        "slug": "central-ohio-infosec-2026",
        "short_description": "Regional security summit serving the Central Ohio infosec community.",
        "start_date": "2026-06-19",
        "end_date": "2026-06-19",
        "city": "Columbus",
        "state": "OH",
        "venue": "TBD",
        "website_url": "https://www.centralohioissa.org/",
        "cfp_url": "",
        "registration_cost_min": 0,
        "registration_cost_max": 50,
        "registration_cost_notes": "Estimated — low-cost regional event",
        "is_estimated_pricing": True,
        "category_tags": ["community", "enterprise"],
        "data_confidence": "low",
        "last_verified": "2026-03-14",
    },
    {
        "id": "ringzer0-2026",
        "name": "RingZer0 2026",
        "slug": "ringzer0-2026",
        "short_description": "Technical training and talks during pre-DEF CON week in Las Vegas.",
        "start_date": "2026-07-31",
        "end_date": "2026-08-01",
        "city": "Las Vegas",
        "state": "NV",
        "venue": "TBD",
        "website_url": "https://ringzer0.training/",
        "cfp_url": "",
        "registration_cost_min": 500,
        "registration_cost_max": 1200,
        "registration_cost_notes": "Estimated — training-heavy event",
        "is_estimated_pricing": True,
        "category_tags": ["hacking", "training"],
        "data_confidence": "low",
        "last_verified": "2026-03-14",
    },
    {
        "id": "black-hat-usa-2026",
        "name": "Black Hat USA 2026",
        "slug": "black-hat-usa-2026",
        "short_description": "Premier enterprise security conference featuring cutting-edge research and training.",
        "start_date": "2026-08-01",
        "end_date": "2026-08-06",
        "city": "Las Vegas",
        "state": "NV",
        "venue": "Mandalay Bay Convention Center",
        "website_url": "https://www.blackhat.com/us-26/",
        "cfp_url": "https://www.blackhat.com/us-26/call-for-papers.html",
        "registration_cost_min": 2595,
        "registration_cost_max": 5595,
        "registration_cost_notes": "Estimated — briefings + training combo",
        "is_estimated_pricing": True,
        "category_tags": ["enterprise", "hacking", "training"],
        "data_confidence": "medium",
        "last_verified": "2026-03-14",
    },
    {
        "id": "bsides-lv-2026",
        "name": "BSides Las Vegas 2026",
        "slug": "bsides-lv-2026",
        "short_description": "Community-driven security event running alongside Black Hat and DEF CON.",
        "start_date": "2026-08-04",
        "end_date": "2026-08-05",
        "city": "Las Vegas",
        "state": "NV",
        "venue": "Tuscany Suites & Casino",
        "website_url": "https://www.bsidesLV.org/",
        "cfp_url": "",
        "registration_cost_min": 0,
        "registration_cost_max": 50,
        "registration_cost_notes": "Estimated — donation-based community event",
        "is_estimated_pricing": True,
        "category_tags": ["community", "hacking"],
        "data_confidence": "medium",
        "last_verified": "2026-03-14",
    },
    {
        "id": "defcon-34",
        "name": "DEF CON 34",
        "slug": "defcon-34",
        "short_description": "The world's largest underground hacking conference.",
        "start_date": "2026-08-06",
        "end_date": "2026-08-09",
        "city": "Las Vegas",
        "state": "NV",
        "venue": "Las Vegas Convention Center",
        "website_url": "https://defcon.org/",
        "cfp_url": "https://defcon.org/html/defcon-34/dc-34-cfp.html",
        "registration_cost_min": 440,
        "registration_cost_max": 440,
        "registration_cost_notes": "Estimated ~$440 cash at the door — exact price TBA",
        "is_estimated_pricing": True,
        "category_tags": ["hacking", "community"],
        "data_confidence": "medium",
        "last_verified": "2026-03-14",
    },
    {
        "id": "appsec-usa-2026",
        "name": "AppSec USA 2026 (OWASP)",
        "slug": "appsec-usa-2026",
        "short_description": "OWASP's flagship North American application security conference.",
        "start_date": "2026-09-14",
        "end_date": "2026-09-17",
        "city": "San Jose",
        "state": "CA",
        "venue": "TBD",
        "website_url": "https://owasp.org/events/",
        "cfp_url": "",
        "registration_cost_min": 495,
        "registration_cost_max": 1295,
        "registration_cost_notes": "Estimated — community to full pass",
        "is_estimated_pricing": True,
        "category_tags": ["enterprise", "training"],
        "data_confidence": "low",
        "last_verified": "2026-03-14",
    },
    {
        "id": "toorcon-2026",
        "name": "ToorCon 2026",
        "slug": "toorcon-2026",
        "short_description": "San Diego hacker conference focused on technical research and community.",
        "start_date": "2026-09-18",
        "end_date": "2026-09-20",
        "city": "San Diego",
        "state": "CA",
        "venue": "TBD",
        "website_url": "https://toorcon.net/",
        "cfp_url": "",
        "registration_cost_min": 75,
        "registration_cost_max": 175,
        "registration_cost_notes": "Estimated",
        "is_estimated_pricing": True,
        "category_tags": ["hacking", "community"],
        "data_confidence": "low",
        "last_verified": "2026-03-14",
    },
    {
        "id": "secureworld-philadelphia-2026",
        "name": "SecureWorld Philadelphia 2026",
        "slug": "secureworld-philadelphia-2026",
        "short_description": "Regional enterprise security conference with CPE-eligible sessions.",
        "start_date": "2026-09-24",
        "end_date": "2026-09-25",
        "city": "Philadelphia",
        "state": "PA",
        "venue": "Greater Philadelphia Expo Center",
        "website_url": "https://www.secureworldexpo.com/events/philadelphia",
        "cfp_url": "",
        "registration_cost_min": 195,
        "registration_cost_max": 395,
        "registration_cost_notes": "Estimated — full conference pass",
        "is_estimated_pricing": True,
        "category_tags": ["enterprise", "training"],
        "data_confidence": "medium",
        "last_verified": "2026-03-14",
    },
    {
        "id": "grrcon-2026",
        "name": "GrrCon 2026",
        "slug": "grrcon-2026",
        "short_description": "Midwest hacker and security community conference in Grand Rapids.",
        "start_date": "2026-10-08",
        "end_date": "2026-10-09",
        "city": "Grand Rapids",
        "state": "MI",
        "venue": "DeVos Place Convention Center",
        "website_url": "https://grrcon.com/",
        "cfp_url": "",
        "registration_cost_min": 50,
        "registration_cost_max": 150,
        "registration_cost_notes": "Estimated",
        "is_estimated_pricing": True,
        "category_tags": ["hacking", "community"],
        "data_confidence": "medium",
        "last_verified": "2026-03-14",
    },
    {
        "id": "wild-west-hackin-fest-2026",
        "name": "Wild West Hackin' Fest 2026",
        "slug": "wild-west-hackin-fest-2026",
        "short_description": "Unique security conference in Deadwood, South Dakota with a Western theme.",
        "start_date": "2026-10-20",
        "end_date": "2026-10-23",
        "city": "Deadwood",
        "state": "SD",
        "venue": "Deadwood Mountain Grand Hotel",
        "website_url": "https://wildwesthackinfest.com/",
        "cfp_url": "",
        "registration_cost_min": 349,
        "registration_cost_max": 499,
        "registration_cost_notes": "Estimated — all-inclusive event",
        "is_estimated_pricing": True,
        "category_tags": ["hacking", "community", "training"],
        "data_confidence": "medium",
        "last_verified": "2026-03-14",
    },
    {
        "id": "sans-cyber-defense-2026",
        "name": "SANS Cyber Defense Forum 2026",
        "slug": "sans-cyber-defense-2026",
        "short_description": "SANS summit focused on defensive security, blue team operations, and SOC.",
        "start_date": "2026-11-09",
        "end_date": "2026-11-10",
        "city": "Washington",
        "state": "DC",
        "venue": "TBD",
        "website_url": "https://www.sans.org/cyber-security-summit/cyber-defense/",
        "cfp_url": "",
        "registration_cost_min": 595,
        "registration_cost_max": 995,
        "registration_cost_notes": "Estimated — SANS summit pricing",
        "is_estimated_pricing": True,
        "category_tags": ["enterprise", "training"],
        "data_confidence": "low",
        "last_verified": "2026-03-14",
    },
]


def main():
    out_dir = os.path.join(os.path.dirname(__file__), "output")
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, "conferences_raw.json")
    with open(out_path, "w") as f:
        json.dump(CONFERENCES, f, indent=2)
    print(f"Wrote {len(CONFERENCES)} conferences to {out_path}")


if __name__ == "__main__":
    main()
